---

- hosts: all
  become: true
  tasks:

  - name: Install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install docker (Ubuntu)
    shell:
      sudo apt-get install docker.io -y
    when: ansible_distribution == "Ubuntu"

  - name: Install docker (CentOS)
    yum:
      name: docker
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install docker sdk
    shell:
      pip3 install docker-py

  - name: Add docker to group
    shell:
      sudo groupadd docker
 
  - name: Add docker to the current user
    shell:
      sudo usermod -aG docker angela

  - name: Docker restarting / enabling
    service:
      name: docker
      state: restarted
      enabled: true

  - name: create build directory
    file:
      path: /root/demo-dockerfile
      path: /root/demo-dockerfile2
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: copy Dockerfile
    copy:
      src: ./dockerfile
      src: ./dockerfile2
      dest: /root/demo-dockerfile/dockerfile
      owner: root
      group: root
      mode: '0644'

